name: slack CI

on:
  workflow_dispatch:
  schedule:
  - cron: "0 6 1-7 * 1" # 세계 표준시 기준으로 06시, 매월 첫 번째 주 월요일은 한국시간 첫번째 주 월요일 오후 3시
  
jobs:
  post_announcement_message:
    runs-on: ubuntu-latest
    steps:
      - name: action code checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
      
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: run main.py
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        run: python3 main.py
